/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    areas: Area;
    posts: Post;
    authors: Author;
    faqs: Faq;
    reviews: Review;
    redirects: Redirect;
    media: Media;
    leads: Lead;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    blog: Blog;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * One document per /services/[slug] landing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * The URL segment. Generated from the name if left empty. Changing it on a published page automatically leaves a 301 behind at the old address.
   */
  slug: string;
  /**
   * Display name, e.g. "Sofa Removal".
   */
  name: string;
  /**
   * Two-digit order key, e.g. "03". Also drives sort order.
   */
  num: string;
  /**
   * One sentence used on /services and in listings.
   */
  blurb: string;
  /**
   * The descriptive heading, e.g. "Sofa removal in Dubai from any floor".
   */
  h1: string;
  /**
   * The paragraph under the display heading. Plain text. Inline links use [label](/path).
   */
  intro: string;
  /**
   * The <h2> sections of the page, in order.
   */
  body?:
    | {
        heading: string;
        paragraphs?:
          | {
              /**
               * Plain text. Inline links use [label](/path).
               */
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What we usually take on this job.
   */
  typical: string;
  crew: string;
  time: string;
  /**
   * Page-specific questions. Two or more are needed before FAQPage structured data is emitted.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as "Also worth a look", in this order.
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * Shown as "Where we do this most", in this order.
   */
  popularAreas?: (number | Area)[] | null;
  /**
   * The two display lines of the band at the bottom of the page.
   */
  cta: {
    line1: string;
    line2: string;
  };
  /**
   * Photo for this page and its social card. Optional — a placeholder is drawn when empty.
   */
  image?: (number | null) | Media;
  /**
   * Search and social metadata for this page.
   */
  seo: {
    /**
     * Aim for 60 characters or fewer so Google does not truncate it. Hard limit 80.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer. Hard limit 200.
     */
    description: string;
    /**
     * Optional. Absolute URL or site-relative path. Leave empty to use this page’s own URL.
     */
    canonical?: string | null;
    /**
     * Ask search engines not to index this page. It is also removed from the sitemap.
     */
    noIndex?: boolean | null;
    /**
     * Optional. Replaces the generated social share image (1200×630 works best).
     */
    ogImage?: (number | null) | Media;
    /**
     * Optional. Defaults to the SEO title.
     */
    ogTitle?: string | null;
    /**
     * Optional. Defaults to the SEO description.
     */
    ogDescription?: string | null;
  };
  /**
   * Homepage explorer group. Leave empty to keep this service off the homepage explorer.
   */
  group?:
    | ('junk-removal' | 'furniture-sofa' | 'appliances' | 'garbage-waste' | 'garden-waste' | 'clearance' | 'same-day')
    | null;
  /**
   * Set to Business to emit schema.org BusinessAudience on this page.
   */
  audience?: 'business' | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One document per /areas/[slug] landing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: number;
  /**
   * The URL segment. Generated from the name if left empty. Changing it on a published page automatically leaves a 301 behind at the old address.
   */
  slug: string;
  /**
   * Display name, e.g. "Dubai Marina".
   */
  name: string;
  /**
   * Two-digit order key, e.g. "01". Also drives sort order.
   */
  num: string;
  /**
   * Short line shown next to the area in lists, e.g. "Tower pickups with service-lift booking handled."
   */
  note: string;
  h1: string;
  /**
   * The paragraph under the display heading. Plain text. Inline links use [label](/path).
   */
  intro: string;
  /**
   * The <h2> sections of the page, in order.
   */
  body?:
    | {
        heading: string;
        paragraphs?:
          | {
              /**
               * Plain text. Inline links use [label](/path).
               */
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Page-specific questions. Two or more are needed before FAQPage structured data is emitted.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as "What we pick up here", in this order.
   */
  popularServices?: (number | Service)[] | null;
  /**
   * Lateral links to neighbouring areas.
   */
  nearbyAreas?: (number | Area)[] | null;
  /**
   * The two display lines of the band at the bottom of the page.
   */
  cta: {
    line1: string;
    line2: string;
  };
  /**
   * Photo for this page and its social card. Optional — a placeholder is drawn when empty.
   */
  image?: (number | null) | Media;
  /**
   * Search and social metadata for this page.
   */
  seo: {
    /**
     * Aim for 60 characters or fewer so Google does not truncate it. Hard limit 80.
     */
    title: string;
    /**
     * Aim for 160 characters or fewer. Hard limit 200.
     */
    description: string;
    /**
     * Optional. Absolute URL or site-relative path. Leave empty to use this page’s own URL.
     */
    canonical?: string | null;
    /**
     * Ask search engines not to index this page. It is also removed from the sitemap.
     */
    noIndex?: boolean | null;
    /**
     * Optional. Replaces the generated social share image (1200×630 works best).
     */
    ogImage?: (number | null) | Media;
    /**
     * Optional. Defaults to the SEO title.
     */
    ogTitle?: string | null;
    /**
     * Optional. Defaults to the SEO description.
     */
    ogDescription?: string | null;
  };
  map: {
    x: number;
    y: number;
  };
  home?: {
    /**
     * Show this area on the homepage map and in the footer.
     */
    featured?: boolean | null;
    x?: number | null;
    y?: number | null;
    /**
     * Tile order on the homepage grid.
     */
    order?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photography for service, area and homepage slots. Alt text is required.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the photo for someone who cannot see it — "Two Junk Services Dubai crew carrying a grey sofa into a covered truck". No keyword lists.
   */
  alt: string;
  /**
   * Optional. Shown under the image where the layout allows it.
   */
  caption?: string | null;
  seedKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Blog posts. A cover image is required before a post can be published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The URL segment. Generated from the name if left empty. Changing it on a published page automatically leaves a 301 behind at the old address.
   */
  slug: string;
  title: string;
  /**
   * One or two sentences. Shown on /blog and used as the meta description unless the SEO tab overrides it. Aim for 160 characters.
   */
  excerpt: string;
  /**
   * Required to publish. Also the default social card for this post.
   */
  coverImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Create the person under Authors first.
   */
  author: number | Author;
  /**
   * Set automatically on first publish. Change it only to correct the record.
   */
  publishedAt?: string | null;
  /**
   * Links back into the service pages this post is about.
   */
  relatedServices?: (number | Service)[] | null;
  relatedAreas?: (number | Area)[] | null;
  /**
   * Search and social metadata for this page.
   */
  seo?: {
    /**
     * Aim for 60 characters or fewer so Google does not truncate it. Hard limit 80.
     */
    title?: string | null;
    /**
     * Aim for 160 characters or fewer. Hard limit 200.
     */
    description?: string | null;
    /**
     * Optional. Absolute URL or site-relative path. Leave empty to use this page’s own URL.
     */
    canonical?: string | null;
    /**
     * Ask search engines not to index this page. It is also removed from the sitemap.
     */
    noIndex?: boolean | null;
    /**
     * Optional. Replaces the generated social share image (1200×630 works best).
     */
    ogImage?: (number | null) | Media;
    /**
     * Optional. Defaults to the SEO title.
     */
    ogTitle?: string | null;
    /**
     * Optional. Defaults to the SEO description.
     */
    ogDescription?: string | null;
  };
  /**
   * Counted from the body on every save.
   */
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The people who write posts. Used for the byline and for Person structured data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * The URL segment. Generated from the name if left empty. Changing it on a published page automatically leaves a 301 behind at the old address.
   */
  slug: string;
  /**
   * As it should appear in the byline.
   */
  name: string;
  /**
   * Optional, e.g. "Operations lead".
   */
  role?: string | null;
  /**
   * A sentence or two. Shown under the post and used in Person structured data.
   */
  bio?: string | null;
  /**
   * Optional headshot.
   */
  photo?: (number | null) | Media;
  /**
   * Full URLs of profiles this person actually owns (LinkedIn, etc.).
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions and answers. Leave both relationships empty for a site-wide question.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  q: string;
  a: string;
  /**
   * Optional link shown under the answer. Both fields are needed for it to render.
   */
  more?: {
    /**
     * Site-relative path, e.g. /how-it-works
     */
    href?: string | null;
    label?: string | null;
  };
  service?: (number | null) | Service;
  area?: (number | null) | Area;
  /**
   * Lowest first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real customer reviews. Nothing renders until "verified" is checked.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * The customer’s own words. Do not rewrite them.
   */
  quote: string;
  /**
   * As the customer published it.
   */
  name: string;
  /**
   * Area · Service, e.g. "JVC · Sofa removal".
   */
  meta?: string | null;
  /**
   * Where it was published (URL or platform). Required evidence for "verified".
   */
  source?: string | null;
  rating?: number | null;
  /**
   * Lowest first.
   */
  order?: number | null;
  /**
   * Tick only when the review exists at the source above. Unticked reviews never render.
   */
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Send an old URL to a new one. Applied to any path that does not match a live page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * The old path, starting with a slash: /old-page. No domain, no query string.
   */
  from: string;
  /**
   * Where it should land: a path like /services/sofa-removal, or a full https:// URL.
   */
  to: string;
  /**
   * Permanent is sent as 308, temporary as 307 — the modern equivalents of 301 and 302.
   */
  type: '301' | '302';
  /**
   * Why this exists. Filled in automatically for slug changes.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Requests sent from the contact form. Newest first. The customer also receives a WhatsApp hand-off at the moment they submit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  /**
   * As typed by the customer.
   */
  phone: string;
  /**
   * Chosen from the area list, or "Other".
   */
  area?: string | null;
  time?: string | null;
  /**
   * The customer’s own description.
   */
  items?: string | null;
  /**
   * Track the request as you work it.
   */
  status?: ('new' | 'contacted' | 'booked' | 'closed') | null;
  /**
   * Internal only. Never shown to the customer.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'areas';
        value: number | Area;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  num?: T;
  blurb?: T;
  h1?: T;
  intro?: T;
  body?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  typical?: T;
  crew?: T;
  time?: T;
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  relatedServices?: T;
  popularAreas?: T;
  cta?:
    | T
    | {
        line1?: T;
        line2?: T;
      };
  image?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noIndex?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  group?: T;
  audience?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  num?: T;
  note?: T;
  h1?: T;
  intro?: T;
  body?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  popularServices?: T;
  nearbyAreas?: T;
  cta?:
    | T
    | {
        line1?: T;
        line2?: T;
      };
  image?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noIndex?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  map?:
    | T
    | {
        x?: T;
        y?: T;
      };
  home?:
    | T
    | {
        featured?: T;
        x?: T;
        y?: T;
        order?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  relatedServices?: T;
  relatedAreas?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noIndex?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  q?: T;
  a?: T;
  more?:
    | T
    | {
        href?: T;
        label?: T;
      };
  service?: T;
  area?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  meta?: T;
  source?: T;
  rating?: T;
  order?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  seedKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  area?: T;
  time?: T;
  items?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Business identity, contact details and the facts used in structured data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Falls back to "Junk Services Dubai".
   */
  siteName?: string | null;
  tagline?: string | null;
  /**
   * Four digits, e.g. 2020.
   */
  foundingYear?: string | null;
  /**
   * Search and social metadata for this page.
   */
  defaultSeo?: {
    /**
     * Aim for 60 characters or fewer so Google does not truncate it. Hard limit 80.
     */
    title?: string | null;
    /**
     * Aim for 160 characters or fewer. Hard limit 200.
     */
    description?: string | null;
    /**
     * Optional. Absolute URL or site-relative path. Leave empty to use this page’s own URL.
     */
    canonical?: string | null;
    /**
     * Ask search engines not to index this page. It is also removed from the sitemap.
     */
    noIndex?: boolean | null;
    /**
     * Optional. Replaces the generated social share image (1200×630 works best).
     */
    ogImage?: (number | null) | Media;
    /**
     * Optional. Defaults to the SEO title.
     */
    ogTitle?: string | null;
    /**
     * Optional. Defaults to the SEO description.
     */
    ogDescription?: string | null;
  };
  /**
   * As displayed, e.g. +92 336 709 1357.
   */
  phone?: string | null;
  /**
   * Full wa.me link.
   */
  whatsapp?: string | null;
  /**
   * Leave empty until the registered address is confirmed. Nothing is published from a partly filled address.
   */
  address?: {
    streetAddress?: string | null;
    addressLocality?: string | null;
    addressRegion?: string | null;
    postalCode?: string | null;
    /**
     * Two-letter country code, e.g. AE.
     */
    addressCountry?: string | null;
  };
  /**
   * Both values are needed before coordinates are published.
   */
  geo?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  /**
   * One row per set of days, e.g. Monday–Sunday 08:00–20:00.
   */
  openingHours?:
    | {
        days: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday')[];
        /**
         * 24-hour, e.g. 08:00
         */
        opens: string;
        /**
         * 24-hour, e.g. 20:00
         */
        closes: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Full profile URLs the business actually owns.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  siteImages?: {
    /**
     * Wide photo beside the “the crew” section on the homepage.
     */
    crewLoadingSofa?: (number | null) | Media;
    /**
     * Tall photo beside the About page intro.
     */
    crewOnSite?: (number | null) | Media;
    /**
     * Small photo on the homepage clearance card.
     */
    clearanceApartments?: (number | null) | Media;
    /**
     * Small photo on the homepage clearance card.
     */
    clearanceVillas?: (number | null) | Media;
    /**
     * Small photo on the homepage clearance card.
     */
    clearanceOffices?: (number | null) | Media;
    /**
     * Small photo on the homepage clearance card.
     */
    clearanceCommercial?: (number | null) | Media;
    /**
     * The cluttered room. Shoot both photos from the same spot so the slider lines up.
     */
    beforeRoom?: (number | null) | Media;
    /**
     * The same room cleared. The slider only appears as photos when both are set.
     */
    afterRoom?: (number | null) | Media;
  };
  /**
   * The content value of the google-site-verification meta tag. Wired up in plan.md Phase 15.
   */
  googleSiteVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header and footer links. Leave empty to keep the built-in navigation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primary?:
    | {
        label: string;
        /**
         * Site-relative path, e.g. /services
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        /**
         * Used from Phase 12 onwards; today only the links render.
         */
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The heading, standfirst and metadata of /blog. Posts are managed under Posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  /**
   * The descriptive heading of the index page.
   */
  h1?: string | null;
  /**
   * The paragraph under the heading. Plain text; inline links use [label](/path).
   */
  intro?: string | null;
  /**
   * Shown when no posts are published yet. The page stays out of search results until one is.
   */
  emptyState?: string | null;
  /**
   * Search and social metadata for this page.
   */
  seo?: {
    /**
     * Aim for 60 characters or fewer so Google does not truncate it. Hard limit 80.
     */
    title?: string | null;
    /**
     * Aim for 160 characters or fewer. Hard limit 200.
     */
    description?: string | null;
    /**
     * Optional. Absolute URL or site-relative path. Leave empty to use this page’s own URL.
     */
    canonical?: string | null;
    /**
     * Ask search engines not to index this page. It is also removed from the sitemap.
     */
    noIndex?: boolean | null;
    /**
     * Optional. Replaces the generated social share image (1200×630 works best).
     */
    ogImage?: (number | null) | Media;
    /**
     * Optional. Defaults to the SEO title.
     */
    ogTitle?: string | null;
    /**
     * Optional. Defaults to the SEO description.
     */
    ogDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  foundingYear?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noIndex?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  phone?: T;
  whatsapp?: T;
  address?:
    | T
    | {
        streetAddress?: T;
        addressLocality?: T;
        addressRegion?: T;
        postalCode?: T;
        addressCountry?: T;
      };
  geo?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  openingHours?:
    | T
    | {
        days?: T;
        opens?: T;
        closes?: T;
        id?: T;
      };
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  siteImages?:
    | T
    | {
        crewLoadingSofa?: T;
        crewOnSite?: T;
        clearanceApartments?: T;
        clearanceVillas?: T;
        clearanceOffices?: T;
        clearanceCommercial?: T;
        beforeRoom?: T;
        afterRoom?: T;
      };
  googleSiteVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  h1?: T;
  intro?: T;
  emptyState?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noIndex?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}